### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by solarssk** [peetereczek/ztm#25]
Cześć!
Czy tylko u mnie przestała działać integracja z API od ZTMu? Czy ktoś też ma ten sam przypadek?
Ostatni pomyślny odczyt był 31.10 o 11:29, od tamtego momentu już cisza. 

configuration.yaml
```
sensor:
  - platform: ztm
    api_key: XXX
    entries: 3
    name: "ZTM"
    lines:
      - number: XXX
        stop_id: XXXX
        stop_number: "01"
      - number: XXX
        stop_id: XXXX
        stop_number: "05"
      - number: XXX
        stop_id: XXXX
        stop_number: "15" 
```

Logs:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 153, in async_update
    self._timetable = self.map_results(res.get('response', [0]))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 226, in map_results
    return [parse_raw_timetable(row) for row in response['result']]
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 232, in parse_raw_timetable
    for val in raw_result['values']:
               ~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

I co jakiś czas też od wczoraj:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 153, in async_update
    self._timetable = self.map_results(res.get('response', [0]))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 226, in map_results
    return [parse_raw_timetable(row) for row in response['result']]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

**Comment by miedzeszyn** [comment]
Hi
So, not only me :)
I can confirm the same issue. Also, have no data for waste collection schedule, so could be that something in API provided by Warszawa has been changed.

**Comment by solarssk** [comment]
Yap... Maybe in Monday I will get more information from IT department in Warsaw municipality.

**Comment by MG-PL-MG** [comment]
Hi, 
any luck with checking the issue with WAW IT ? I can only confirm last info form api was 31.10 and no update since then. 

I generated query and sent it from browser and got a reply so api seems to work. So maybe reply structure changed somehow thus not recognized by integration ?

the example in documentation is like this:
<img width="550" alt="image" src="https://github.com/user-attachments/assets/a1ef6780-03fc-4165-8278-b0907be5d94d">
 so value followed by key and started by "values"
In the reply I get has this structure:
<img width="303" alt="image" src="https://github.com/user-attachments/assets/e55826a2-b4b7-43c4-ad7b-ad3705467071">
so key followed by value and no "values" at the beginning.

not sure if this is an issue.

**Comment by 1Bogdan1** [comment]
![{BD26FF6F-F295-4DE6-9804-F47B7E366F40}](https://github.com/user-attachments/assets/f541e10e-b8c1-4228-89df-3a01bcdf98b8)

**Comment by mgorsk1** [comment]
I have recently refactored the code and for me this issue is not present, can you check?

https://github.com/peetereczek/ztm/pull/24/files

<img width="564" alt="image" src="https://github.com/user-attachments/assets/0aec5f2b-001e-48bd-8f56-a2d4561cccca">

**Comment by MG-PL-MG** [comment]
I'm newbie here so not sure how to validate things but I have copied all the files in to my HA and sensor is almost back to normal got up to date information but can't see the destination. 

`sensor:
  - platform: ztm
    api_key:*************
    entries: 4
    lines:
      - number: 189
        stop_id: 4011
        stop_number: "06"`

![image](https://github.com/user-attachments/assets/614f6993-2da0-4b69-aa77-ac5e905ff791)

**Comment by mgorsk1** [comment]
thanks for letting me know @MG-PL-MG - it seems that 'kierunek' field is now missing from the response of ztm api, sadly nothing I can do about it.

**Comment by 1Bogdan1** [comment]
> Niedawno dokonałem refaktoryzacji kodu i u mnie ten problem nie występuje. Czy możesz to sprawdzić?
> 
> https://github.com/peetereczek/ztm/pull/24/files
> 
> <img alt="obraz" width="564" src="https://private-user-images.githubusercontent.com/5680655/383974006-0aec5f2b-001e-48bd-8f56-a2d4561cccca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzA3NDYsIm5iZiI6MTczMTA3MDQ0NiwicGF0aCI6Ii81NjgwNjU1LzM4Mzk3NDAwNi0wYWVjNWYyYi0wMDFlLTQ4YmQtOGY1Ni1hMmQ0NTYxY2NjY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMTI1NDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTYwZDNjNDIzOGUxMTYxNjczNDBhZjc5N2I0ZGU3MzVhZjBkNzRhOGQwMzY0MmU5NWFmZDBkNmIwNjJlODg2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YbWx4sTpGAjyrEbUkF6_mCkobv6Q6mZUAaSwiyxN-xU">

I confirm - after re -invoicing everything works correctly.

**Comment by m-wyz** [comment]
How did you built version from PR? In HA I see possibility to download only branches from master, not PR made by someone else.
For now waiting for @peetereczek  to merge :)

**Comment by solarssk** [comment]
After observing this in two weeks - it works fifty fifty :/ 

![Screenshot 2024-11-24 at 09 06 26](https://github.com/user-attachments/assets/509b97ac-c661-473c-bc2a-6f4914b7348a)

In my area I have bus stop which only works in workday.

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:944
First occurred: November 23, 2024 at 10:43:43 PM (622 occurrences)
Last logged: 9:04:44 AM

Update for sensor.ztm_1XX_from_XXXX_XX fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 166, in async_update
    departures_data = await self.client.get()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/client.py", line 50, in get
    for reading in json_response["result"]:
TypeError: 'NoneType' object is not iterable

```
also error at HA restart:

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:189
First occurred: November 23, 2024 at 10:43:43 PM (1 occurrences)
Last logged: November 23, 2024 at 10:43:43 PM

Detected that custom integration 'ztm' closes the Home Assistant aiohttp session at custom_components/ztm/client.py, line 36: async with self._session as session:, please create a bug report at https://github.com/peetereczek/ztm/issues
```

**Comment by peetereczek** [comment]
Hi, I have merged this pull request from @mgorsk1 to master. You can pull latest master for now. Thank you @mgorsk1 for contribution! Good job!
I'll make some release before Christmas, maybe fine-tuning some stuff around HA. I'm sorry for not being active here

> I have recently refactored the code and for me this issue is not present, can you check?
> 
> https://github.com/peetereczek/ztm/pull/24/files
>

**Comment by solarssk** [comment]
Thanks mate!

**Comment by solarssk** [comment]
Hey :) @mgorsk1 
Is it possible to check this issue?

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:324
First occurred: 1:41:46 PM (1 occurrences)
Last logged: 1:41:46 PM

Detected that custom integration 'ztm' closes the Home Assistant aiohttp session at custom_components/ztm/client.py, line 36: async with self._session as session:. Please create a bug report at https://github.com/peetereczek/ztm/issues
```

**Comment by skupu** [comment]
@peetereczek Is it done?

**Comment by Michuu** [comment]
I've downloaded the current master branch and I can confirm it fixed the problem. However, I also tested setting 
`return_type: TIME_OF_DEPARTURE`
which leads to the following error:
```
2025-01-22 22:51:09.106 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ztm_143_from_2098_01 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 180, in async_update
    self._state = str(self._get_departure_value(departures[0])) if departures[0].time_to_depart <= 60 else "60+"
                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 163, in _get_departure_value
    return reading.astimezone(local_timezone).strftime("%H:%M")
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'ZTMDepartureDataReading' object has no attribute 'astimezone'
```

**Comment by wododoporny** [comment]
Stupid question or maybe user erro, should this work?

![Image](https://github.com/user-attachments/assets/d6db2261-0e3d-4deb-83de-fb77cfd424bf)

```
Update for sensor.ztm_245_from_1304_01 fails
Update for sensor.ztm_145_from_1304_01 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 139, in async_update
    self._timetable = self.map_results(res.get('response', [0]))
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 212, in map_results
    return [parse_raw_timetable(row) for row in response['result']]
            ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/config/custom_components/ztm/sensor.py", line 218, in parse_raw_timetable
    for val in raw_result['values']:
               ~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by WRLPDZ** [comment]
Hi,
I have redownload main version 0.2.2 but problem still occure.

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:960
First occurred: 8:38:18 PM (696 occurrences)
Last logged: 9:06:18 PM

Update for sensor.ztm_518_from_1016_02 fails
Update for sensor.ztm_211_from_1016_01 fails
Update for sensor.ztm_705_from_6075_05 fails
Update for sensor.ztm_211_from_1015_02 fails
Update for sensor.ztm_326_from_6075_05 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 139, in async_update
    self._timetable = self.map_results(res.get('response', [0]))
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 212, in map_results
    return [parse_raw_timetable(row) for row in response['result']]
            ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/config/custom_components/ztm/sensor.py", line 218, in parse_raw_timetable
    for val in raw_result['values']:
               ~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str`

**Comment by WRLPDZ** [comment]
Update:

I have downloaded files from git and put them manually in component folder.
It work for now.

**Comment by WRLPDZ** [comment]
Today not working again

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:960
First occurred: 2:22:54 AM (2775 occurrences)
Last logged: 5:46:55 PM

Update for sensor.ztm_326_from_1016_01 fails
Update for sensor.ztm_326_from_1015_02 fails
Update for sensor.ztm_326_from_6075_05 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 166, in async_update
    departures_data = await self.client.get()
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/client.py", line 50, in get
    for reading in json_response["result"]:
                   ~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not iterable`

Is there any way to resolve this problem permanently or just delete it and forget?

**Comment by klimak000** [comment]
Update to master from 0.2.2 solved issue

**Comment by WRLPDZ** [comment]
@klimak000 
> Update to master from 0.2.2 solved issue

So what version do you have now? I do not see any described as Master.

![Image](https://github.com/user-attachments/assets/896f9d17-9d64-401c-853e-757ffdaa27be)

And 0.2.2 just reinstalled still gives errors

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:960
First occurred: 21:00:27 (911 occurrences)
Last logged: 21:37:27

Update for sensor.ztm_705_from_1016_01_2 fails
Update for sensor.ztm_705_from_6005_15_2 fails
Update for sensor.ztm_731_from_1016_02_2 fails
Update for sensor.ztm_516_from_1016_02_2 fails
Update for sensor.ztm_735_from_6075_05_2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/config/custom_components/ztm/sensor.py", line 139, in async_update
    self._timetable = self.map_results(res.get('response', [0]))
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ztm/sensor.py", line 212, in map_results
    return [parse_raw_timetable(row) for row in response['result']]
            ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/config/custom_components/ztm/sensor.py", line 218, in parse_raw_timetable
    for val in raw_result['values']:
               ~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str`

**Comment by klimak000** [comment]
@WRLPDZ 

I updated code manually by command line.

Something like that:
mkdir temp
git clone https://github.com/peetereczek/ztm
cp custom_components/ztm/* /config/custom_componets/ztm

**Comment by WRLPDZ** [comment]
@klimak000 It is the same as I have, and its not working form me :(
I have also try to manually download and add it to HA without success. 
Still the same error.

**Comment by essys** [comment]
I experienced the same issue and I fixed it for myself by following the manual installation process described in the readme:
```
If you want to do that manually, download the files from custom_components/ztm into your $homeassistant_config_dir/custom_components/ztm
Once downloaded and configured as per below information, you'll need to restart HomeAssistant to have the custom component and the sensors of ztm platform taken into consideration.
```
Just copy the content of each file from current [master](https://github.com/peetereczek/ztm/tree/master/custom_components/ztm) to your HACS custom component in /homeassistant/custom_components/ztm/...

Once each file is updated and your HA was rebooted you can continue with the configurarion as described.
It works for me.
